/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#define LOG_TAG "System.out"
/* Header for class com_player_xingfeng_multimedia_Mp3Encoder */

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

#ifndef _Included_com_player_xingfeng_multimedia_Mp3Encoder
#define _Included_com_player_xingfeng_multimedia_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_player_xingfeng_multimedia_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_player_xingfeng_multimedia_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
